### ISSUE TITLE
released binary and compile instructions for Linux are not available

### ISSUE THREAD

**Issue by qtlin** [cryply/cryply-wallet#1]
I was able to build dynamic executable using instructions in
https://www.ndchost.com/wiki/how-to-install-bitcoin-on-centos-7
and
https://stackoverflow.com/questions/35007134/c-boost-undefined-reference-to-boostfilesystemdetailcopy-file
However src/qt/test folder does not compile because its Makefile does not honor PKG_CONFIG_PATH=/opt/openssl/lib/pkgconfig configure option and can't find openssl include files unless explicitly specified in CXXFLAGS like
export CXXFLAGS="-DBOOST_NO_CXX11_SCOPED_ENUMS -I/opt/openssl/include"
Interestingly, cryply does not compile with openssl-1.1.0g, is it by design?
Please make openssl library linked to application statically, or document the process of doing it, in order to be able to distribute cryply-qt without specially build libssl.so.1.0.0

**Comment by lolfinger** [comment]
any logs?

**Comment by qtlin** [comment]
I apologize but no logs after 24 days.
Please follow build instructions and logs will be in in front of you.
I haven't done anything besides following above instructions.

**Comment by cryply** [comment]
https://github.com/cryply/cryply-wallet/commit/749c1941b8f5232ea2d88260344a1a5eaccc67c2
