### ISSUE TITLE
Fails to build against boost 1.66.0

### ISSUE THREAD

**Issue by qtlin** [cryply/cryply-wallet#2]
please see https://github.com/gridcoin/Gridcoin-Research/issues/803 and https://github.com/gridcoin/Gridcoin-Research/commit/14c5880ab357367b9bcc16c83922ea14796f3cdf for an identical problem description and solution.
in addition there appears to be another problem with 1.66.0 like this https://github.com/magnetwork/magnet/issues/12

**Comment by cryply** [comment]
https://github.com/cryply/cryply-wallet/commit/ba817f155c0afbf4010b6f2bcd599b32a0b23d29
